env:
  global:
    - CC_TEST_REPORTER_ID=12ea26bfc6e20c9fbf057ae70b4848c9bf5d196f45160ad30daf9321ab93764a
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database blog_api_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
language: ruby
rvm:
  - 2.5
services:
  - postgresql
