version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: ruby:2.5
        environment:
        - PG_HOST=localhost
        - PG_USER=ubuntu
        - RAILS_ENV=test
        - POSTGRES_USER=ubuntu
      # The following example uses the official postgres 9.6 image, you may also use circleci/postgres:9.6
      # which includes a few enhancements and modifications. It is possible to use either image .
      - image: postgres:9.6.5
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_DB=blog_api_test
    steps:
      - checkout
      - run:
          name: Install Ruby Dependencies
          command: bundle install
      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create db:schema:load --trace
            bundle exec rake db:migrate
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/blog_api_test"
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rspec spec/
      - store_test_results:
          path: /tmp/test-results
